<?php

include "db.php";

#$array = array('dharani.manne@gmail.com','institutewebops@gmail.com', 'me12b040@smail.iitm.ac.in', 'avi.kondeti@gmail.com', 'hvvivek2007@gmail.com');
$array = array('chiru6753@gmail.com','saikiranp321@gmail.com');

foreach( $array as $to ){
  /*$body = "Hello,<br><br>

    Your Placement Reps account has been created. Your Log In credentials are:<br>

    Link: http://placement.iitm.ac.in/reps<br>
    Username: Your Roll Number<br>
    Password: Your Roll Number In Capital Letters<br><br><br>

    Regards<br>
    Institute WebOps";
   */
  $body = "Hey,<br><br>
            
    <p>This is a test email generated by Dharani Manne. Please do bear with me until I finish testing mail service properly.</p><br>
    
    Regards<br>
    Institute WebOps
    ";
  $ldapuser = 'me12b040';
  $ldappwd = 'ip-$3P8C';
  $replymail = 'institutewebops@gmail.com';
  $replyname = 'Institute WebOps';
  $frommail = 'webops@smail.iitm.ac.in';
  $fromname = 'Institute WebOps';
  //  $to = $row['mail'];
  $subj = 'Reps Portal Login credentials';

  include "testemail.php";
}


/* mail('drake.mandin@gmail.com', 'the subject', 'the message', null,'-f test@students.iitm.ac.in');
echo "Done";
 */

?>
